---
deployment:
  tasks:
    - export DEPLOYPATH=/home/triotbdw/dev.trionxai.com/wp-content/themes/king
    #- /bin/cp -R wp-content $DEPLOYPATH
    rsync -avu wp-content/ /home/triotbdw/dev.trionxai.com/wp-content/
